
#Unstable features.
#If you met any issues with VS, please disable unstable features first before reporting to VS or other mods' repo.
[unstable]

	#Ship recycle settings
	[unstable.recycle]
		#Reuse deleted ship's chunks to assemble new ships when possible.
		#Warn: Compatible issues may occur if enabled, only report issues when this is set to false.
		reuse_ship_chunks = false
		#Recycle ships that no longer contains any blocks.
		recycle_empty_ships = true

